### ISSUE TITLE
"ValueError: I2S port is already in use"

### ISSUE THREAD

**Issue by mdaeron** [miketeachman/micropython-esp32-i2s-examples#12]
If for some reason my code exits without calling `I2S.deinit()`, after I soft-reboot the board (crtl-D in REPL) I get the following message:

```
ValueError: I2S port is already in use
```

Apart from a hard reboot (unplugging and replugging my USB cable), is there a more elegant way to deinit() I2S?

**Comment by miketeachman** [comment]
You could reset the ESP32 in the REPL.  That might be a better method compared to unplugging/plugging the USB cable?
```
import machine
machine.reset()
```

**Comment by miketeachman** [comment]
Workaround provided.

**Comment by miketeachman** [comment]
The latest commit removes the need for a hard reset.
