### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by OPHoperHPO** [miketeachman/micropython-esp32-i2s-examples#13]
Hello, @miketeachman. Is it possible somehow programmatically from micropython to adjust the volume of the sound coming from the speakers?

**Comment by miketeachman** [comment]
Hi,
It is definitely possible.  Please take a look at a post I made on the MicroPython Forum:
https://forum.micropython.org/viewtopic.php?f=18&t=8406&hilit=i2s+volume
Hopefully this helps.
