### ISSUE TITLE
Can no longer merge PR in mainline micropython

### ISSUE THREAD

**Issue by mdaeron** [miketeachman/micropython-esp32-i2s-examples#21]
I used to be able to build firmware for the TinyPICO with:

````sh
git clone https://github.com/micropython/micropython.git
cd micropython
git fetch origin pull/4471/head:esp32_i2s
git checkout master
git merge esp32_i2s
````

Now this yields a conflict in `ports/esp32/modmachine.c`. I can change things manually, but I was wondering if there's a simpler, automated way to do so.

**Comment by miketeachman** [comment]
thanks for reporting this @mdaeron !   

I'll rebase to the latest MicroPython commit and fix the conflict.

**Comment by miketeachman** [comment]
I've fixed the conflict and updated the PR.  Thanks again for reporting this problem.

**Comment by mdaeron** [comment]
No problem. Thanks to you, actually: having I2S on micropython is really nice. I hope it gets incorporated into mainline soon.
