### ISSUE TITLE
max9837a on the t-watch

### ISSUE THREAD

**Issue by uraich** [miketeachman/micropython-esp32-i2s-examples#22]
This is just to tell you that I managed to get your I2S driver to work on the t-watch 2020

**Comment by miketeachman** [comment]
Fantastic !   Thanks for letting me know.  Very nice work.

**Comment by uraich** [comment]
Well, it was **you** who has done the nice work! I only assembled the bits and pieces in a custom version of MicroPython and made **your** example run.
I will now check if I convert this into an internet radio.
Many thanks for your driver and greetings from Austria
