### ISSUE TITLE
Example works on Wondom AA-AB32255 AMPLIFIER BOARD & DAC - TAS5756

### ISSUE THREAD

**Issue by robjordan** [miketeachman/micropython-esp32-i2s-examples#8]
Hi Mike

Thanks so much for these examples. Just wanted to note that I tested the 'play stereo' example against the above mentioned I2S DAC / Amp and it worked first time. Boy did I get a surprise when that sample wav boomed out, no volume control yet!

Just 3 I2S signals + Gnd & 3v3. I haven't connected MCLK yet, it's optional with this board, though I'm not sure the implication for jitter if unconnected.

Anyhow, just mentioning in case you want to note it as a tested device.
[http://store.sure-electronics.com/product/AA-AB32255](http://store.sure-electronics.com/product/AA-AB32255)

**Comment by miketeachman** [comment]
thanks for the update on your project @robjordan!  That looks like an excellent board to pair with an ESP32.  I added the board to the list of tested devices.

**Comment by miketeachman** [comment]
updated documentation
